[package]
name = "mdbook-diff2html"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
mdbook = { version = "0.4", default-features = false }
pulldown-cmark = { version = "0.9", default-features = false }
clap = { version = "4", default-features = false }
serde_json = "1"
semver = "1"
anyhow = "1"
