cargo-features = ["named-profiles", "profile-overrides"]

[workspace]
members = [
  "pie",
  "graph",
  "dev_shared",
  "dev_shared_external",
]
default-members = [
  "pie",
  "graph",
  "dev_shared",
  "dev_shared_external",
]
resolver = "2"
