[package]
name = "pie_graph"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
thunderdome = "0.5"
fnv = "1"

[dev-dependencies]
pretty_env_logger = "0.4"
