[package]
name = "pie"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
pie_graph = { path = "../graph" }
pie_tagged_serde = { path = "../tagged_serde" }
dyn-clone = "1"
serde = "1"
erased-serde = "0.3"
linkme = "0.3"
lazy_static = "1"

[dev-dependencies]
rstest = "0.15"
tempfile = "3"
assert_matches = "1"
serde_json = "1"
