[package]
name = "pie"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
pie_graph = { path = "../graph" }
dyn-clone = "1"
serde = { version = "1", features = ["derive"], optional = true }
erased-serde = { version = "0.3", optional = true }

[dev-dependencies]
rstest = "0.15"
tempfile = "3"
assert_matches = "1"
serde_json = "1"

[features]
default = ["serde"]
serde = ["dep:serde", "dep:erased-serde", "pie_graph/serde"]
