[package]
name = "pie"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
pie_graph = { path = "../graph" }
serde = "1"
sha2 = "0.10"
walkdir = "2"

[dev-dependencies]
rstest = "0.15"
tempfile = "3"
assert_matches = "1"
ron = "0.8"
