[package]
name = "pie"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
pie_graph = { path = "../graph" }
serde = { version = "1", optional = true }
sha2 = { version = "0.10", optional = true }
walkdir = { version = "2", optional = true }

[dev-dependencies]
dev_shared = { path = "../dev_shared" }
dev_shared_external = { path = "../dev_shared_external" }
serde = "1"
rstest = "0.18"
tempfile = "3"
assert_matches = "1"
ron = "0.8"
criterion = { version = "0.4", features = ["html_reports"] }

[features]
default = ["recursive_stampers", "hash_stampers", "serde"]
serde = ["dep:serde"]
recursive_stampers = ["dep:walkdir"]
hash_stampers = ["dep:sha2"]

[[bench]]
name = "topdown_bottomup_scalability"
harness = false

[[bench]]
name = "file_dependency_scalability"
harness = false
