[package]
name = "pie"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
pie_graph = { path = "../graph" }
dyn-clone = "1"

[dev-dependencies]
rstest = "0.15"
tempfile = "3"
